### ISSUE TITLE
Go not usable directly after update-golang.sh 

### ISSUE THREAD

**Issue by x1mdev** [udhos/update-golang#23]
Hi,

I've tried to embed your Golang script in one of my own install scripts that runs on a rpi3. `update-golang.sh` finishes successful, but I'm not able to use go commands such as `go env`, `go version` or `go get github.com/dev/tool` .. After a reboot it seems to work and I can install the tools. Any ideas/solution for this issue?

**Comment by udhos** [comment]
Hi!

The script adds the location of go tools into the PATH env var by creating this file:

    /etc/profile.d/golang_path.sh

One could make go tools immediately usable in the current shell by sourcing the file:

    . /etc/profile.d/golang_path.sh

Does this solve your case?

**Comment by x1mdev** [comment]
Just got a fresh rpi image, let me take a look!

**Comment by x1mdev** [comment]
Hi @udhos, it seems to work!

I've added this line to my install script:
```
source . /etc/profile.d/golang_path.sh
```
It might not be very graceful but it works :p 
The only error I'm getting is this but it does seem to work:

`main: line 79: source: .: is a directory`

**edit**

I think I either fixed it with something else because `. /etc/profile.d/golang_path.sh` needs to be executed and i don't think it executes using `source . /etc/profile.d/golang_path.sh` does that.. :')

**Comment by udhos** [comment]
Cool, I am closing the issue then. Let me know if you spot anything else.

**Comment by x1mdev** [comment]
Will do, thanks for the quick response :)
