### ISSUE TITLE
archive is not removed after installation

### ISSUE THREAD

**Issue by adntgv** [udhos/update-golang#25]
I have noticed that downloaded archive is not deleted after successful golang upgrade.
Archive is stored as /usr/local/go1.15.5.linux-amd64.tar.gz, had to manually remove it.
I imagine that archives would pile up clogging the directory

**Comment by udhos** [comment]
Yes, the downloaded file is kept as cache:

"Downloaded releases are kept as cache under '/usr/local'. You can erase them manually."
https://github.com/udhos/update-golang#how-it-works
