### ISSUE TITLE
GoLang update from 1.10 to latest

### ISSUE THREAD

**Issue by bharathtnt** [udhos/update-golang#27]
Hi Team,
What all the factors  should we consider before updating go lang version to the latest.
Please help us with this.
Thank You.

**Comment by udhos** [comment]
> Hi Team,
> What all the factors should we consider before updating go lang version to the latest.
> Please help us with this.
> Thank You.

If you are asking about upgrading the golang toolchain in a system, all you need is to run this update-golang.sh script.

If you are asking about upgrading one application from Go 1.10 to 1.16 then it might be a simple or a huge task, it is going to depend on the complexity of your application. I don't think anyone could give you a detailed recipe for this. If you give your source code to an experienced Go developer he will be able to discover all the details by trying to build and run your software with latest Go version.
