### ISSUE TITLE
GitHub Sponsors

### ISSUE THREAD

**Issue by elenalape** [udhos/update-golang#32]
I have gone through the agony of quitting vim.

I have burned down a couple of houses running Android Studio.

I have seen code so bad it made me want to quit programming.

But nothing, _nothing_ in my career compares to the struggles I’ve endured trying to manually update golang.

This script brought tears of joy for me and presumably thousands of others who have ⭐ this repo. Have you considered signing up for [GitHub Sponsors](https://github.com/sponsors) so we have a way to thank you?!

**Comment by udhos** [comment]
Thank you for such kind words.
Actually I have rarely seen such a generous expression of gratitude.
At this point I don't feel inclined to get sponsoring for this modest work.
But please rest assured you made my day bright in a way that no money could!
