### ISSUE TITLE
sha256sum: WARNING: 1 computed checksum did NOT match

### ISSUE THREAD

**Issue by samirkape** [udhos/update-golang#36]
I cloned the repo 3 times and tried verifying the checksum but it is not matching, any idea what might be the reason?

**Comment by udhos** [comment]
What SHA256 value do yout get for these commands below?

```bash
$ sha256sum update-golang.sh
06bd86ebed47f567d53c4fe22e76fd25d30a79dbcda067ea5a94f5c105577951  update-golang.sh
```

```
$ curl https://raw.githubusercontent.com/udhos/update-golang/master/update-golang.sh.sha256
06bd86ebed47f567d53c4fe22e76fd25d30a79dbcda067ea5a94f5c105577951  update-golang.sh
```

**Comment by samirkape** [comment]
```
sha256sum update-golang.sh
3a985a9fae35c58952979431c2106ef563aeb469b2b120fbb3e265bae52545d2 *update-golang.sh
```

```
curl https://raw.githubusercontent.com/udhos/update-golang/master/update-golang.sh.sha256
22806bd86ebed47f567d53c4fe22e76fd25d30a79dbcda067ea5a94f5c105577951  update-golang.sh
```

Platform: Windows (gitbash)

**Comment by udhos** [comment]
I guess the issue with wrong sha256 for git clone is your git client is likely configured to translate line endings to Windows convention, and that affects the digest.

The issue with curl I can't guess!

However, as far as I can tell, this update-golang script is NOT able to correctly install/update Go under Windows. For Windows you should really rely on the official installation instructions.

**Comment by samirkape** [comment]
Thank you for the info.
Closing this since the windows platform isn't supported
