### ISSUE TITLE
After Updating to 1.20 static analysis gave "fatal error: 'stdlib.h' file not found"

### ISSUE THREAD

**Issue by veqqq** [udhos/update-golang#37]
When `fatal error: 'stdlib.h' file not found` appears, there is a problem with cgo. Core gnu compilers are included here. The error is simple to fix with: `sudo apt-get install build-essential`

Now, that should have already been installed (since I had no previous issue) and I can't see how the script would have affected it. For this reason, I did not make a commit with this on line 542 of update-golang.sh, but perhaps others encounter this issue and something similar would be necessary.

**Comment by udhos** [comment]
Perhaps this change disrupted static analysis:

> The go command now disables cgo by default on systems without a C toolchain. Consequently, when Go is installed on a system without a C compiler, it will now use pure Go builds for packages in the standard library that optionally use cgo, instead of using pre-distributed package archives (which have been removed, as noted above).

https://go.dev/blog/go1.20
