### ISSUE TITLE
Example of two versions installed at once?

### ISSUE THREAD

**Issue by francislavoie** [udhos/update-golang#38]
Sometimes I need to A/B test something across two Go versions, say latest and latest - 1, to compare for regressions.

How would you recommend running this to keep two versions installed?

Would be nice if I could have `go1.19` in my PATH plus `go` as the latest version, for example.

And what would be the best way to wipe out the secondary installations?

I'm sure it can be done with the env vars config, but I think it would be helpful to have an explanation in the README.

**Comment by udhos** [comment]
Well, one can easily switch among many versions by running:

```
sudo RELEASE=1.20.1 ./update-golang.sh ;# install and cache 1.20.1
sudo RELEASE=1.20.2 ./update-golang.sh ;# install and cache 1.20.2
sudo RELEASE=1.20.1 ./update-golang.sh ;# switch back to 1.20.1
sudo RELEASE=1.20.2 ./update-golang.sh ;# switch back to 1.20.2
```

Once a version is cached locally, switching to it takes around 5s, on my machine.

Can you afford to switch versions like that?

**Comment by gedw99** [comment]
this might be useful

https://github.com/kevincobain2000/gobrew

been using it for CI and local 

it can reflect on the FS and load the go version you want also.
