### ISSUE TITLE
change /usr/local/go check

### ISSUE THREAD

**Issue by puzanov** [udhos/update-golang#7]
in my local machine /usr/local/go is a directory, not a symlink. so the script fails with 
``rm: cannot remove '/usr/local/go': Is a directory``
you can handle it and move the dir to /tmp or ~ and continue the script.

**Comment by udhos** [comment]
Please test this commit: https://github.com/udhos/update-golang/commit/cbc2090f14c2cdf14f12ebc9ff69190a121c7940

**Comment by puzanov** [comment]
yep, it's working, thanks!

**Comment by udhos** [comment]
Thanks for reporting!
