### ISSUE TITLE
Checksum did not match?

### ISSUE THREAD

**Issue by uLan08** [udhos/update-golang#9]
I checked for the checksum, following the one in the docs and I got 
```
$ update-golang.sh: FAILED
$ sha256sum: WARNING: 1 computed checksum did NOT match
```
What to do after this? Sorry for the noob question, kind of new in sum checking.

**Comment by udhos** [comment]
The checksum was wrong indeed.
It has been fixed now.
Thanks for reporting.

**Comment by udhos** [comment]
@uLan08 Is it ok to close this ticket?

**Comment by uLan08** [comment]
Yes, gladly.
